import './index.scss'
import './index.pug'
import './blocks/standart-buttons/standart-buttons'
import './blocks/percentage/percentages'
import './blocks/sliders/sliders'
import './blocks/stages/stages'
import './blocks/form-elements/form-elements'