import './index.scss'
import './index.pug'
import './blocks/standart-buttons/button_cyan-small-ripple/button_cyan-small-ripple'
import './blocks/standart-buttons/button_cyan-big-ripple/button_cyan-big-ripple'
import './blocks/standart-buttons/button_orange-small-ripple/button_orange-small-ripple'
import './blocks/standart-buttons/button_orange-big-ripple/button_orange-big-ripple'

import './blocks/percentage/percentages'
import './blocks/sliders/sliders'
import './blocks/stages/stages'